services:
  image_uploader:
    image: notfullmetal/imageuploader:latest
    command: fastapi run image_uploader.py
    restart: on-failure
    # ports:
    # -  "8000:8000"
    networks:
      - app-network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - image_uploader
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: