name: Image Uploader
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GH_IMAGE_REPOSITORY: ghcr.io/${{ github.repository }}
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUN }}
          password: ${{ secrets.DOCKERPW }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
  

      - name: Build & Push image
        run: |
          docker buildx build --platform linux/amd64 \
          -t notfullmetal/imageuploader:${{ env.SHORT_SHA }} \
          -t notfullmetal/imageuploader:${{ github.ref_name }} \
          -t notfullmetal/imageuploader:latest \
          -t $GH_IMAGE_REPOSITORY:${{ env.SHORT_SHA }} \
          -t $GH_IMAGE_REPOSITORY:${{ github.ref_name }} \
          -t $GH_IMAGE_REPOSITORY:latest \
          . --push

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}




